set(SDK_INSTALL_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../..")
set(HOST_SYSROOT    "${SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux")
set(TARGET_SYSROOT  "${SDK_INSTALL_DIR}/sysroots/armv8a-poky-linux")
set(HOST_BIN        "${HOST_SYSROOT}/usr/bin")
set(TOOLCHAIN_NAME  "aarch64-poky-linux")
set(GCC_DIR         "${HOST_BIN}/${TOOLCHAIN_NAME}")

set(CMAKE_SYSTEM_NAME       Linux)
set(CMAKE_SYSTEM_PROCESSOR "aarch64")

set(CMAKE_C_COMPILER    "${GCC_DIR}/${TOOLCHAIN_NAME}-gcc")
set(CMAKE_CXX_COMPILER  "${GCC_DIR}/${TOOLCHAIN_NAME}-g++")

set(ARCH_FLAGS          " -march=armv8-a+crc+crypto")
set(CMAKE_C_FLAGS       "${ARCH_FLAGS}" CACHE STRING "" FORCE )
set(CMAKE_CXX_FLAGS     "${ARCH_FLAGS}" CACHE STRING "" FORCE )
set(CMAKE_ASM_FLAGS     ${CMAKE_C_FLAGS} CACHE STRING "" FORCE )
set(CMAKE_LDFLAGS_FLAGS ${CMAKE_C_FLAGS} CACHE STRING "" FORCE )

set(CMAKE_SYSROOT "${TARGET_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH "${TARGET_SYSROOT}" )

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )

set(CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX "")

set(CMAKE_PROGRAM_PATH "${HOST_SYSROOT}/usr/bin" CACHE STRING "" FORCE)
